apiVersion: v1
kind: Service
metadata:
  name: kuben-service
  namespace: kubenlabb
spec:
  selector:
    app: kuben
  ports:
    - name: application
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP